import pandas as pd
import matplotlib.pyplot as plt
from scipy.spatial.distance import minkowski
import numpy as np
import math
import unittest
import time

print("A1\n")
#generated by Chatgpt Ai

"""
Study the data columns (features) and identify whether each feature is Nominal, Ordinal, Interval, or Ratio, the marketing_campaign dataset can be classified as follows:

Feature	            Type of Data	                    Measurement Scale
ID	            Customer Identifier	                      Nominal
Year_Birth	     Birth Year	                            Interval
Education	    Basic, Graduation, Master, PhD, etc.      Ordinal
Marital_Status	Single, Married, Divorced, etc.	        Nominal
Income	            Annual Income	                      Ratio
Kidhome	        Number of Kids at Home	                  Ratio
Teenhome	    Number of Teenagers at Home	              Ratio
Dt_Customer	    Date of Customer Enrollment	              Interval
Recency     	Days Since Last Purchase	               Ratio
MntWines	    Amount Spent on Wine	                   Ratio
MntFruits	    Amount Spent on Fruits	                   Ratio
MntMeatProducts	Amount Spent on Meat Products	          Ratio
MntFishProducts	Amount Spent on Fish Products	          Ratio
MntSweetProducts	Amount Spent on Sweet Products	      Ratio
MntGoldProds	Amount Spent on Gold Products	          Ratio
NumDealsPurchases	Number of Purchases Made with Deals	  Ratio
NumWebPurchases	    Number of Web Purchases	              Ratio
NumCatalogPurchases	Number of Catalog Purchases	          Ratio
NumStorePurchases	Number of Store Purchases	          Ratio
NumWebVisitsMonth	Number of Website Visits per Month	  Ratio
AcceptedCmp3	Accepted Campaign 3 (0/1)	            Nominal
AcceptedCmp4	Accepted Campaign 4 (0/1)	            Nominal
AcceptedCmp5	Accepted Campaign 5 (0/1)	            Nominal
AcceptedCmp1	Accepted Campaign 1 (0/1)	            Nominal
AcceptedCmp2	Accepted Campaign 2 (0/1)	            Nominal
Complain	Complaint Filed (0/1)	                    Nominal
Z_CostContact	Contact Cost	                         Ratio
Z_Revenue	Revenue Generated	                         Ratio
Response	Campaign Response (0/1)	                    Nominal

"""
#generated by Chatgpt Ai

print("A2\n")
# Label Encoding Function
def label_encoding(column):
    unique_values = column.unique()
    mapping = {value: index for index, value in enumerate(unique_values)}
    encoded_column = column.map(mapping)
    return encoded_column, mapping

# One-Hot Encoding Function
def one_hot_encoding(column):
    encoded_df = pd.get_dummies(column, prefix=column.name)
    return encoded_df

# Sample categorical data
data = pd.DataFrame({'Education': ['Graduation', 'PhD', 'Master', 'Graduation', 'Basic']})

# Label Encoding
label_encoded, mapping = label_encoding(data['Education'])

print("Label Encoded Column:")
print(label_encoded)

print("\nMapping:")
print(mapping)

# One-Hot Encoding
one_hot_encoded = one_hot_encoding(data['Education'])

print("\nOne-Hot Encoded Data:")
print(one_hot_encoded)
print("\n")

#generated by Chatgpt Ai
print("A3\n")
df = pd.read_excel("Lab Session Data.xlsx",sheet_name="marketing_campaign")

# Original dataset dimensions
print("Original Dataset Shape:", df.shape)

# Create copies of dataset
label_df = df.copy()
one_hot_df = df.copy()

# Identify categorical columns
categorical_columns = df.select_dtypes(include=['object']).columns

print("\nCategorical Columns:")
print(list(categorical_columns))

# Apply Label Encoding using A2 function
for col in categorical_columns:
    label_df[col], mapping = label_encoding(label_df[col])

print("\nShape after Label Encoding:")
print(label_df.shape)

# Apply One-Hot Encoding using A2 function
for col in categorical_columns:
    encoded_columns = one_hot_encoding(one_hot_df[col])

    one_hot_df = pd.concat(
        [one_hot_df.drop(col, axis=1), encoded_columns],
        axis=1
    )

print("\nShape after One-Hot Encoding:")
print(one_hot_df.shape)

# Dimensionality comparison
print("\nDimensionality Analysis")
print("Original Dataset :", df.shape)
print("Label Encoded Dataset :", label_df.shape)
print("One-Hot Encoded Dataset :", one_hot_df.shape)
print("\n")


#generated by Chatgpt Ai
print("A4\n")
# Minkowski Distance Function
def minkowski_distance(a, b, p):
    if len(a) != len(b):
        raise ValueError("Vectors must have the same length")

    distance = sum(abs(a[i] - b[i]) ** p for i in range(len(a)))
    return distance ** (1 / p)

# Sample vectors
a = [1, 2, 4]
b = [4, 5, 6]
print("Manhattan Distance (p=1):", minkowski_distance(a, b, 1))
print("Euclidean Distance (p=2):", minkowski_distance(a, b, 2))
print("Minkowski Distance (p=3):", minkowski_distance(a, b, 3))
print("\n")


#generated by Chatgpt Ai
print("A5\n")
df = pd.read_excel("Lab Session Data.xlsx",sheet_name="marketing_campaign")

# Take any two feature vectors from the dataset
a = df.iloc[0].select_dtypes(include=['number']) if False else df.iloc[0]
b = df.iloc[1]
# Keep only numeric features
numeric_df = df.select_dtypes(include=['int64', 'float64'])

a = numeric_df.iloc[0].values
b = numeric_df.iloc[1].values

# Calculate Minkowski distances for p = 1 to 10
p_values = list(range(1, 11))
distances = []

for p in p_values:
    distances.append(minkowski_distance(a, b, p))

# Plot p vs Minkowski Distance
plt.figure(figsize=(8, 5))
plt.plot(p_values, distances, marker='o')
plt.title("Minkowski Distance vs p")
plt.xlabel("p")
plt.ylabel("Minkowski Distance")
plt.grid(True)
plt.show()
print("\n")

#generated by Chatgpt Ai
print("A6\n")
df = pd.read_excel("Lab Session Data.xlsx",sheet_name="marketing_campaign")
numeric_df = df.select_dtypes(include=['int64', 'float64'])

a = numeric_df.iloc[0].values
b = numeric_df.iloc[1].values
# Suitable value of p
p = 3

# Using user-defined function from A4
custom_distance = minkowski_distance(a, b, p)

# Using SciPy function
scipy_distance = minkowski(a, b, p)

# Display results
print("Custom Minkowski Distance :", custom_distance)
print("SciPy Minkowski Distance  :", scipy_distance)

# Difference between the two
print("Difference :", abs(custom_distance - scipy_distance))
print("\n")


#generated by Chatgpt Ai
print("A7\n")
# Dot Product Function
def dot_product(vec1, vec2):
    if len(vec1) != len(vec2):
        raise ValueError("Vectors must have the same length")
    result = 0
    for i in range(len(vec1)):
        result += vec1[i] * vec2[i]
    return result

# Euclidean Norm Function
def euc_Norm(vec):
    sum_sq = 0
    for value in vec:
        sum_sq += value ** 2
    return math.sqrt(sum_sq)

# Given vectors
vec1 = [2, 3, 4, 5]
vec2 = [5, 6, 7, 8]

# Manual calculations
manual_dot = dot_product(vec1, vec2)
manual_norm_vec1 = euc_Norm(vec1)
manual_norm_vec2 = euc_Norm(vec2)

# NumPy calculations
numpy_dot = np.dot(vec1, vec2)
numpy_norm_vec1 = np.linalg.norm(vec1)
numpy_norm_vec2 = np.linalg.norm(vec2)

# Display results
print("----- Dot Product -----")
print("Manual Result :", manual_dot)
print("NumPy Result  :", numpy_dot)

print("\n----- Euclidean Norm -----")
print("Vector 1 Manual :", manual_norm_vec1)
print("Vector 1 NumPy  :", numpy_norm_vec1)

print("\nVector 2 Manual :", manual_norm_vec2)
print("Vector 2 NumPy  :", numpy_norm_vec2)
print("\n")


#generated by Chatgpt Ai
print("A8\n")
# Function to calculate Mean
def calculate_mean(data):
    return sum(data) / len(data)

# Function to calculate Variance
def calculate_variance(data):
    mean = calculate_mean(data)
    variance = sum((x - mean) ** 2 for x in data) / len(data)
    return variance

# Function to calculate Standard Deviation
def calculate_standard_deviation(data):
    variance = calculate_variance(data)
    return math.sqrt(variance)

# for all numerical columns in the dataset
def dataset_statistics(matrix):
    results = {}
    for column in matrix.columns:
        data = matrix[column].dropna().tolist()
        results[column] = {
            "Mean": calculate_mean(data),
            "Variance": calculate_variance(data),
            "Standard Deviation": calculate_standard_deviation(data)
        }
    return pd.DataFrame(results).T

df = pd.read_excel("Lab Session Data.xlsx",sheet_name="marketing_campaign")
# Select only numerical features
numeric_df = df.select_dtypes(include=['int64', 'float64'])
# Calculate statistics
statistics = dataset_statistics(numeric_df)
print(statistics)
print("\n")


#generated by Chatgpt Ai
print("A9\n")
df = pd.read_excel("Lab Session Data.xlsx",sheet_name="marketing_campaign")
numeric_df = df.select_dtypes(include=['int64', 'float64'])

# Mean and Standard Deviation using A8 functions
manual_mean = {}
manual_std = {}

for column in numeric_df.columns:
    data = numeric_df[column].dropna().tolist()
    manual_mean[column] = calculate_mean(data)
    manual_std[column] = calculate_standard_deviation(data)

# Mean and Standard Deviation using Python/Pandas built-in functions
builtin_mean = numeric_df.mean()
builtin_std = numeric_df.std(ddof=0)      

# Comparison Table
comparison = pd.DataFrame({
    "Manual Mean": pd.Series(manual_mean),
    "Built-in Mean": builtin_mean,
    "Manual Std Dev": pd.Series(manual_std),
    "Built-in Std Dev": builtin_std
})
print(comparison)


#generated by Chatgpt Ai
print("A10\n")
df = pd.read_excel("Lab Session Data.xlsx",sheet_name="marketing_campaign")
feature = df['Income'].dropna()

mean_value = calculate_mean(feature.tolist())
variance_value = calculate_variance(feature.tolist())

print("Feature Selected : Income")
print("Mean :", mean_value)
print("Variance :", variance_value)

# Histogram using NumPy
hist_values, bin_edges = np.histogram(feature, bins=10)

print("\nHistogram Frequencies:")
print(hist_values)

print("\nBin Edges:")
print(bin_edges)

# Plot Histogram
plt.figure(figsize=(8,5))
plt.hist(feature, bins=10, edgecolor='black')
plt.title("Histogram of Income")
plt.xlabel("Income")
plt.ylabel("Frequency")
plt.grid(True, alpha=0.3)
plt.show()
print("\n")


#generated by Chatgpt Ai
print("A11\n")
# initialize_centroids(data, k)
def initialize_centroids(data, k):
    np.random.seed(42)
    random_indices = np.random.choice(len(data), k, replace=False)
    centroids = data[random_indices]
    return centroids

# assign_clusters(data, centroids)
# Uses previously defined minkowski_distance(..., p=2)
def assign_clusters(data, centroids):
    cluster_labels = []
    for point in data:
        distances = []
        for centroid in centroids:
            distance = minkowski_distance(point, centroid, 2)
            distances.append(distance)
        cluster_labels.append(np.argmin(distances))
    return np.array(cluster_labels)

# update_centroids(data, cluster_labels, k)
def update_centroids(data, cluster_labels, k):
    centroids = []
    for cluster in range(k):
        cluster_points = data[cluster_labels == cluster]
        if len(cluster_points) > 0:
            centroid = np.mean(cluster_points, axis=0)
        else:
            centroid = data[np.random.randint(len(data))]
        centroids.append(centroid)
    return np.array(centroids)

# kmeans(data, k)
def kmeans(data, k, max_iterations=100):
    centroids = initialize_centroids(data, k)
    for _ in range(max_iterations):
        cluster_labels = assign_clusters(data, centroids)
        new_centroids = update_centroids(
            data,
            cluster_labels,
            k
        )
        if np.allclose(centroids, new_centroids):
            break
        centroids = new_centroids
    return cluster_labels, centroids

df = pd.read_excel("Lab Session Data.xlsx",sheet_name="marketing_campaign")
numeric_df = df.select_dtypes(include=['int64', 'float64'])
# Remove missing values
numeric_df = numeric_df.dropna()
# Convert to matrix
data = numeric_df.values
# Number of clusters
k = 3
start=time.time()
labels, centroids = kmeans(data, k)
end=time.time()
total_time=end-start
print("Cluster Labels:")
print(labels)
print("\nCentroids:")
print(centroids)
print("\nCluster Counts:")
print(pd.Series(labels).value_counts().sort_index())
print("total_time take for k-means",total_time)
print("\n")

print("test cases for functions:\n")
# Unit test case for all the functions used in this lab
class TestLabFunctions(unittest.TestCase):
    # label_encoding()
    def test_label_encoding(self):
        column = pd.Series(['A', 'B', 'A', 'C'])
        encoded, mapping = label_encoding(column)
        self.assertEqual(len(encoded), 4)
        self.assertEqual(len(mapping), 3)
        self.assertEqual(encoded[0], encoded[2])

    # one_hot_encoding()
    def test_one_hot_encoding(self):
        column = pd.Series(['Red', 'Blue', 'Red'])
        encoded = one_hot_encoding(column)
        self.assertEqual(encoded.shape[0], 3)
        self.assertEqual(encoded.shape[1], 2)

    # minkowski_distance()
    def test_minkowski_distance(self):
        a = [1, 2, 4]
        b = [4, 5, 6]
        distance = minkowski_distance(a, b, 2)
        self.assertAlmostEqual(
            distance,
            4.69041575982343,
            places=5
        )

    def test_minkowski_distance_invalid(self):
        with self.assertRaises(ValueError):
            minkowski_distance([1, 2], [1, 2, 3], 2)

    # dot_product()
    def test_dot_product(self):
        vec1 = [2, 3, 4, 5]
        vec2 = [5, 6, 7, 8]
        self.assertEqual(
            dot_product(vec1, vec2),
            96
        )

    # euc_Norm()
    def test_euc_norm(self):
        vec = [3, 4]

        self.assertEqual(
            euc_Norm(vec),
            5.0
        )

    # calculate_mean()
    def test_calculate_mean(self):
        data = [1, 2, 3, 4, 5]

        self.assertEqual(
            calculate_mean(data),
            3.0
        )

    # calculate_variance()
    def test_calculate_variance(self):
        data = [1, 2, 3, 4, 5]

        self.assertEqual(
            calculate_variance(data),
            2.0
        )

    # calculate_standard_deviation()
    def test_calculate_standard_deviation(self):
        data = [1, 2, 3, 4, 5]

        self.assertAlmostEqual(
            calculate_standard_deviation(data),
            np.sqrt(2),
            places=5
        )

    # initialize_centroids()
    def test_initialize_centroids(self):
        data = np.array([
            [1, 1],
            [2, 2],
            [3, 3],
            [4, 4]
        ])

        centroids = initialize_centroids(data, 2)
        self.assertEqual(
            centroids.shape,
            (2, 2)
        )

    # assign_clusters()
    def test_assign_clusters(self):
        data = np.array([
            [1, 1],
            [2, 2],
            [8, 8]
        ])

        centroids = np.array([
            [1, 1],
            [8, 8]
        ])

        labels = assign_clusters(
            data,
            centroids
        )

        self.assertEqual(len(labels), 3)

    # update_centroids()
    def test_update_centroids(self):
        data = np.array([
            [1, 1],
            [2, 2],
            [8, 8],
            [9, 9]
        ])

        labels = np.array([
            0,
            0,
            1,
            1
        ])

        centroids = update_centroids(
            data,
            labels,
            2
        )

        self.assertEqual(
            centroids.shape,
            (2, 2)
        )

        self.assertTrue(
            np.allclose(
                centroids[0],
                [1.5, 1.5]
            )
        )

    # kmeans()
    def test_kmeans(self):
        data = np.array([
            [1, 1],
            [1.5, 2],
            [2, 1],
            [8, 8],
            [9, 8],
            [8, 9]
        ])

        labels, centroids = kmeans(
            data,
            2
        )

        self.assertEqual(
            len(labels),
            len(data)
        )

        self.assertEqual(
            centroids.shape,
            (2, 2)
        )


if __name__ == "__main__":
    unittest.main()

